In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Resultado_Geral_2019.csv', sep=';')

/Users/marcello/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
pd.set_option('display.max_columns', None)
df.head()

,CD_ALUNO,NOMEDEP,NomeDepBol,RegiaoMetropolitana,CDREDE,DE,CODMUN,MUN,CODESC,TIPOCLASSE,SERIE,Turma,CLASSE,TP_SEXO,DT_NASCIMENTO,PERIODO,NEC_ESP_1,NEC_ESP_2,NEC_ESP_3,NEC_ESP_4,NEC_ESP_5,Tip_PROVA,Tem_Nec,cad_prova_mat,cad_prova_lp,particip_lp,particip_mat,TOTAL_PONTO_LP,TOTAL_PONTO_MAT,porc_ACERT_lp,porc_ACERT_mat,profic_lp,profic_mat,nivel_profic_lp,nivel_profic_mat,classific_lp,classific_mat,VALIDADE
0,54425,ESTADUAL-SE,Rede Estadual,Interior,20803,BIRIGUI,753,LOURDES,30193,0,9º Ano EF,A,231992702,1,1988-12,MANHÃ,11,0,0,0,0,C,1,12.0,12.0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,199609,ESTADUAL-SE,Rede Estadual,Interior,20313,ITARARE,365,ITABERA,39718,0,EM-3ª série,A,232445155,2,1992-01,MANHÃ,0,0,0,0,0,C,0,16.0,16.0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,190846,ESTADUAL-SE,Rede Estadual,Interior,20305,ITAPEVA,756,NOVA CAMPINA,915117,0,EM-3ª série,A,231099151,2,1980-04,NOITE,0,0,0,0,0,C,0,14.0,14.0,1,0,0,0,0,0,"153,4",NaN,Abaixo do Básico,NaN,Insuficiente,NaN,1
3,317226,ESTADUAL-SE,Rede Estadual,Interior,20301,APIAI,737,BARRA DO CHAPEU,14412,0,EM-3ª série,B,231635806,2,1993-06,NOITE,0,0,0,0,0,C,0,22.0,22.0,1,1,16,12,"66,7",50,"324,9","316,7",Adequado,Básico,Suficiente,Suficiente,1
4,318858,ESTADUAL-SE,Rede Estadual,Interior,20702,FERNANDOPOLIS,444,MERIDIANO,27005,0,EM-3ª série,A,230876617,2,1993-10,MANHÃ,0,0,0,0,0,C,0,22.0,22.0,1,1,13,5,"54,2","20,8","277,6","227,3",Básico,Abaixo do Básico,Suficiente,Insuficiente,1

In [6]:
df.shape

(1337533, 38)